### ISSUE TITLE
/photo/upload endpoint not working

### ISSUE THREAD

**Issue by Soneji** [adw0rd/instagrapi-rest#19]
```sh
curl -X 'POST' \
  'https://api.website.com/photo/upload' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'sessionid=XYZ' \ #session id works
  -F 'file=@file.jpg;type=image/jpeg' \
  -F 'caption=cap'
```

Error: response status is 500
```json
{
  "detail": "{\"message\":\"login_required\",\"status\":\"fail\"}",
  "exc_type": "PhotoNotUpload"
}
```

compose logs are:
```
api_1  | INFO:     None [403] POST https://i.instagram.com/rupload_igphoto/1631650226816_0_1319177777 (203.0.0.29.118, Xiaomi capricorn)
api_1  | ERROR:    Photo Upload failed with the following response: <Response [403]>
api_1  | INFO:     172.28.0.1:44202 - "POST /photo/upload HTTP/1.1" 500 Internal Server Error
api_1  | ERROR:    Exception in ASGI application
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
api_1  |     result = await app(self.scope, self.receive, self.send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
api_1  |     return await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
api_1  |     await super().__call__(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
api_1  |     await self.middleware_stack(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
api_1  |     raise exc from None
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
api_1  |     await self.app(scope, receive, _send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
api_1  |     raise exc from None
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
api_1  |     await self.app(scope, receive, sender)
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
api_1  |     await route.handle(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
api_1  |     await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
api_1  |     response = await func(request)
api_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
api_1  |     raw_response = await run_endpoint_function(
api_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
api_1  |     return await dependant.call(**values)
api_1  |   File "/app/./routers/photo.py", line 138, in photo_upload
api_1  |     return await photo_upload_post(
api_1  |   File "/app/./helpers.py", line 33, in photo_upload_post
api_1  |     return cl.photo_upload(fp.name, **kwargs)
api_1  |   File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/photo.py", line 208, in photo_upload
api_1  |     upload_id, width, height = self.photo_rupload(path, upload_id)
api_1  |   File "/usr/local/lib/python3.8/site-packages/instagrapi/mixins/photo.py", line 170, in photo_rupload
api_1  |     raise PhotoNotUpload(response.text, response=response, **last_json)
api_1  | instagrapi.exceptions.PhotoNotUpload: {"message":"login_required","status":"fail"}
```

It says login required but my token works on the `/auth/timeline_feed` endpoint

**Comment by Soneji** [comment]
Hi @adw0rd 
I think I've found a fix for this. 

In the /photo/upload endpoint, I call `cl.get_timeline_feed()` just before actually uploading the file. This ensures this error does not happen. Should I make a PR with this functionality, or should we leave this to the user to implement on their client?

If we leave it to the user, the built in docs will not work however...

What do you think?

**Comment by adw0rd** [comment]
@Soneji it's great that you found a solution, I think it should be added to https://github.com/adw0rd/instagrapi/. Can you send PR?

**Comment by Soneji** [comment]
closed by https://github.com/adw0rd/instagrapi-rest/pull/20
